version: '3.8'

services:
  db:
    image: mysql:8
    container_name: events_db
    environment:
      MYSQL_DATABASE: events_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sport-network
volumes:
  db_data:
networks:
  sport-network: